### ISSUE TITLE
Forge stuck in 'Discovering mod files'

### ISSUE THREAD

**Issue by VinnyStalck** [JT122406/ArchLoom-Multiloader-Template#1]
Forge runs gets stuck in 'Discovering mod files', stops responding and shows an error.
Do I need to setup something first?

![image](https://github.com/JT122406/ArchLoom-Multiloader-Template/assets/42945819/04d2c56c-35a2-4fd1-aaca-54836e134a05)

```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:209)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.0.30/net.minecraftforge.fml.loading.targets.CommonDevLaunchHandler.findJarOnClasspath(CommonDevLaunchHandler.java:186)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.0.30/net.minecraftforge.fml.loading.targets.ForgeUserdevLaunchHandler.getMinecraftPaths(ForgeUserdevLaunchHandler.java:30)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.0.30/net.minecraftforge.fml.loading.targets.ForgeUserdevLaunchHandler$Client.getMinecraftPaths(ForgeUserdevLaunchHandler.java:51)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.0.30/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:36)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.0.30/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.0.30/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164)
        at MC-BOOTSTRAP/fmlloader@1.20.2-48.0.30/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
        at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
```

Fabric works fine as always

**Comment by JT122406** [comment]
That's odd did you change everything to match your modid?

**Comment by JT122406** [comment]
Arch loom 1.4 Fixed this, Template has been updated
